import pickle
from collections import defaultdict

dfd = defaultdict(list)

dfd["drugs"] = ['buy', 'product', 'store', 'price', 'best', 'offer', 'customer', 'need', 'want', 'high', 'provide', 'purchase', 'try', 'quality', 'weed', 'method', 'guarantee', 'cocaine', 'pure', 'marijuana', 'drug', 'pill', 'white', 'gram', 'ketamine', 'psychedelics', 'bulk', 'toggle', 'finest', 'dmt', 'lsd', 'gdp', 'xanax', 'heroin', 'powder', 'capsule', 'oxycodone', 'kamagra', 'freshly', 'cialis', 'tramadol', 'viagra', 'prescription', 'lab', 'pharma', 'bubblegum', 'kaugummie', 'drugstore', 'weight', 'purity', 'highest', 'oral', 'coke', 'coffee']
dfd["weapons"] = ['large', 'gun', 'guide', 'legal', 'fake', 'dangerous', 'weapon', 'rifle', 'toggle', 'steal', 'gt', 'handgun', 'riffle', 'phishing', 'supplier', 'bullet', 'pgp', 'ganja', 'luger', 'murder', 'killing', 'fight', 'club', 'dangerous', 'knife', 'sharp']
dfd["adult/porn"] = ['want', 'product', 'available', 'security', 'free', 'people', 'body', 'photo', 'little', 'black', 'huge', 'look', 'model', 'oniondir', 'enjoy', 'art', 'western', 'big', 'girl', 'legal', 'shit', 'porn', 'secret', 'party', 'adult', 'nude', 'sex', 'love', 'touch', 'lesbian', 'stocking', 'abuse', 'friend', 'custom', 'son', 'fisting', 'handjob', 'squirting', 'blowjob', 'blonde', 'bi', 'orgasm', 'pleased', 'lolita', 'plumber', 'brunette', 'teen', 'pedo', 'brutal', 'fucked', 'pov', 'mature', 'pornhub', 'latina', 'gangbang', 'sexual', 'whore', 'piss', 'amateur', 'bdsm', 'omegle', 'shemale', 'boy', 'milking', 'lingerie', 'cumshot', 'tit', 'slut', 'naked', 'preteen', 'hottest', 'deepthroat', 'hardporn', 'sexvideos', 'porno', 'dad', 'couple', 'hard', 'fuck', 'bar', 'warning','daughter', 'sexy', 'dirty']
dfd["market"] = ['buy', 'get', 'account', 'store', 'order', 'price', 'offer', 'seller', 'sell', 'customer', 'delivery', 'ship', 'market', 'sale', 'worldwide', 'shop', 'available', 'usd', 'buying', 'internet', 'mobile', 'discount', 'amazon', 'fee', 'ebay', 'galaxy', 'samsung', 'iphone', 'iphones', 'supply', 'brand', 'mastercard', 'passport', 'electronics', 'license', 'android', 'device', 'smartphones', 'mobile']
dfd["scam/crime"] = ['scam', 'crime', 'word', 'safe', 'time', 'secure', 'security', 'people', 'country', 'hacker', 'anonymous', 'hacking', 'someone', 'person', 'fake', 'product', 'cash', 'price', 'customer', 'seller', 'site', 'store', 'bitcoin', 'wallet', 'high', 'pay', 'guarantee', 'scammer', 'fraud', 'deal', 'scammed', 'iphone', 'criminal', 'depending', 'expert', 'specialist', 'return', 'government', 'skill', 'hitman', 'anonymously', 'hide', 'run', 'warranty', 'police', 'highest', 'handgun', 'equipment', 'programming']
dfd["forum/blog"] = ['service', 'site', 'email', 'address', 'forum', 'web', 'security', 'secure', 'tor', 'network', 'welcome', 'list', 'privacy', 'anonymous', 'access', 'post', 'guide', 'browser', 'comment', 'wiki', 'social', 'chat', 'file', 'message', 'name', 'active', 'answer', 'policy', 'issue', 'note', 'status', 'communication', 'share', 'trusted', 'twitter', 'community', 'deepweb', 'deep', 'dark', 'database', 'document', 'proxy', 'bookmark', 'category', 'asked', 'mailing', 'mail']
dfd['financial'] = ['carding', 'store', 'btc', 'service', 'bitcoin', 'payment', 'card', 'account', 'buy', 'order', 'money', 'credit', 'site', 'purchase', 'cash', 'used', 'using', 'delivery', 'bitcoins', 'secure', 'number', 'reserved', 'shop', 'bank', 'access', 'atm', 'wallet', 'mastercard', 'financial', 'moneygram', 'vryptocurrency', 'bill', 'dollar', 'paypal', 'crypto', 'creditcard', 'pay', 'fast', 'site']

with open('category_words.txt', 'wb') as f:
    pickle.dump(dfd, f)